/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "fastexcel-parent"
include(":fastexcel-reader")
include(":fastexcel")
include(":fastexcel-e2e")
project(":fastexcel").projectDir = file("fastexcel-writer")
project(":fastexcel-e2e").projectDir = file("e2e")
