/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.dhatim.java-conventions")
}

dependencies {
    api("com.github.rzymek:opczip:1.2.0")
    testImplementation("org.apache.poi:poi-ooxml:5.2.3")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.2")
    testImplementation("org.assertj:assertj-core:3.24.2")
    testImplementation("commons-io:commons-io:2.11.0")
    testImplementation("org.apache.logging.log4j:log4j-core:2.19.0")
}

description = "Fastexcel Writer"

java {
    withJavadocJar()
}