/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.dhatim.java-conventions")
}

dependencies {
    api(project(":fastexcel"))
    api(project(":fastexcel-reader"))
    testImplementation("commons-io:commons-io:2.11.0")
    testImplementation("org.apache.poi:poi-ooxml:5.2.3")
    testImplementation("org.assertj:assertj-core:3.24.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.2")
    testImplementation("org.openjdk.jmh:jmh-core:1.36")
    testImplementation("org.openjdk.jmh:jmh-generator-annprocess:1.36")
    testImplementation("com.monitorjbl:xlsx-streamer:2.2.0")
}

description = "Fastexcel End-to-End tests"

java {
    withJavadocJar()
}
